server:
  host: "0.0.0.0"      # 监听地址 (0.0.0.0 表示监听所有网络接口)
  port: 8080         # 服务端口

server:
  port: 8080

mysql:
  host: "mysql"          # Docker Compose 中的服务名称
  port: 3306
  user: "root"
  password: "password"
  name: "user_service"

redis:
  host: "redis"          # Docker Compose 中的服务名称
  port: 6379
  password: ""
