version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      CONFIG_PATH: "/app/config/config_docker.yaml"
    depends_on:
      - mysql
      - redis
      
  mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /home/leili/goproject/mygpt/mygpt-back/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql

      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

