version: "3.9"
services:
  app:
    build:
      context: ../../mygpt-back
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_service
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
